//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildCodeMetrics.JetBrains.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildCodeMetrics.JetBrains.UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root CoveredStatements=&quot;626&quot; TotalStatements=&quot;849&quot; CoveragePercent=&quot;74&quot; ReportType=&quot;Xml&quot; DotCoverVersion=&quot;3.1&quot;&gt;
        ///  &lt;Assembly Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;412&quot; TotalStatements=&quot;466&quot; CoveragePercent=&quot;88&quot;&gt;
        ///    &lt;Namespace Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;273&quot; TotalStatements=&quot;323&quot; CoveragePercent=&quot;85&quot;&gt;
        ///      &lt;Type Name=&quot;CodeMetricsRunner&quot; CoveredStatements=&quot;173&quot; TotalStatements=&quot;173&quot; CoveragePercent=&quot;100&quot;&gt;
        ///        &lt;Constructor Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MSBuildCodeMetrics_core_coverage {
            get {
                return ResourceManager.GetString("MSBuildCodeMetrics_core_coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by JetBrains Inspect Code 9.0 Update 1 --&gt;
        ///&lt;Report ToolsVersion=&quot;9.0&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;MSBuildCodeMetrics.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;
        ///    &lt;IssueType Id=&quot;AccessToForEachVariableInClosure&quot; Category=&quot;Potential Code Quality Issues&quot; Description=&quot;Access to foreach variable in closure&quot; Severity=&quot;WARNING&quot; /&gt;
        ///    &lt;IssueType Id=&quot;ArrangeStaticM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MSBuildCodeMetrics_Metrics {
            get {
                return ResourceManager.GetString("MSBuildCodeMetrics_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root CoveredStatements=&quot;626&quot; TotalStatements=&quot;849&quot; CoveragePercent=&quot;74&quot; ReportType=&quot;Xml&quot; DotCoverVersion=&quot;3.1&quot;&gt;
        ///  &lt;Assembly Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;412&quot; TotalStatements=&quot;466&quot; CoveragePercent=&quot;88&quot;&gt;
        ///    &lt;Namespace Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;273&quot; TotalStatements=&quot;323&quot; CoveragePercent=&quot;85&quot;&gt;
        ///      &lt;Type Name=&quot;CodeMetricsRunner&quot; CoveredStatements=&quot;100&quot; TotalStatements=&quot;173&quot; CoveragePercent=&quot;100&quot; /&gt;            
        ///    &lt;/Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartialCoverage1 {
            get {
                return ResourceManager.GetString("PartialCoverage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root CoveredStatements=&quot;626&quot; TotalStatements=&quot;849&quot; CoveragePercent=&quot;74&quot; ReportType=&quot;Xml&quot; DotCoverVersion=&quot;3.1&quot;&gt;
        ///  &lt;Assembly Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;412&quot; TotalStatements=&quot;466&quot; CoveragePercent=&quot;88&quot;&gt;
        ///    &lt;Namespace Name=&quot;MSBuildCodeMetrics.Core&quot; CoveredStatements=&quot;273&quot; TotalStatements=&quot;323&quot; CoveragePercent=&quot;85&quot;&gt;
        ///      &lt;Type Name=&quot;CodeMetricsRunner&quot; CoveredStatements=&quot;73&quot; TotalStatements=&quot;173&quot; CoveragePercent=&quot;100&quot; /&gt;      
        ///    &lt;/Namespace&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartialCoverage2 {
            get {
                return ResourceManager.GetString("PartialCoverage2", resourceCulture);
            }
        }
    }
}
